created font and colors variables and installed bootstrap
WildCodeSchool/js-orleans-p2-elite-star pull request #27
Opened 2020-10-23 19:50 UTC by barthflo

*Ajout des variables pour la typographie et la charte graphique
*Installation de bootstrap
*Reset du body
*Cleaning d'app.jsx

2020-10-23 20:08 UTC, Mo-Mokaddemini approved these changes
Le code est bon

2020-10-24 10:33 UTC, lolarne approved these changes
Ok pour moi

2020-10-24 12:50 UTC, ldupas requested changes

2020-10-24 12:50 UTC, ldupas commented on src/App.css
> +  --grey-medium: rgba(119, 119, 148, 1);
light & medium-light si vous voulez changer de gris pour une autre couleur dans le futur

2020-10-24 13:59 UTC, barthflo commented
Modification des noms de variables suggérés par Louis et ajout de la librairie d'icones react-icons

2020-10-24 15:09 UTC, Mo-Mokaddemini approved these changes

2020-10-24 16:32 UTC, lolarne approved these changes

2020-10-25 08:36 UTC, Mo-Mokaddemini approved these changes

2020-10-25 14:18 UTC, ldupas approved these changes

2020-10-25 14:18 UTC, merged